### ISSUE TITLE
QnA maker

### ISSUE THREAD

**Issue by MarcusMLarsson** [essenbee/Essenbee.ChatBox#1]
The connection with QnA maker does not work for me. Whatever I type, I get "Sorry, it looks like something went wrong." Any tips?

**Comment by essenbee** [comment]
Hi Marcus,

I just ran a quick test, and the connection to my QnAmaker account is working - I got responses back to random questions such as "How are you today?". I'd recommend making sure that you have entered your QnA maker credentials correctly. Drop by my Discord if you still have problems: https://discord.gg/Rz8r93q

Cheers,

Stu

**Comment by MarcusMLarsson** [comment]
Hmm I guess I'm doing something wrong than. Either way, very awesome code and thanks for sharing!

**Comment by MarcusMLarsson** [comment]
Anyway to make the submit button for the adaptive cards to do a Imback /Messageback action similar to a Hero card?

**Comment by essenbee** [comment]
Hi Marcus,

To the best of my knowledge, the submit from an adaptive card is a post back that has to be handles the way I do it in the project. I was unable to find another way, but agree that a model consistent with the bot’s built in cards would be ideal.

Cheers 

Stu

**Comment by MarcusMLarsson** [comment]
OK, I see. Thank you for all the help!
